### ISSUE TITLE
Android App Crashes on Launch. Error - Signature mismatch for package or System.TypeLoadException: Could not load list of method overrides due to Method not found

### ISSUE THREAD

**Issue by quantumarun** [msintuneappsdk/intune-app-sdk-xamarin#30]
I have integrated Intune SDK in my Application. It used to work fine earlier probably a month back but now its crashes on launch.

Below are the nuget package version
Microsoft.Intune.MAM.Remapper.Tasks : 0.1.4428.1
Microsoft.Intune.MAM.Xamarin.Android : 3.0.4428.1
Xamarin.Forms : 4.0.0.482894
All required Xamarin.Android packages are added and are updated to latest version (1.1.1.1 or 28.0.0.1 . as per package versions)

Note: I don't have MAMApplication class in my project.

I have tried both Debug and Release Configs and got different error logs. Same are provided below:

**Debug Config:**
[BundleMarshal] Throwing exception encountered during execution within the Agent's Content Provider.
[s.packagename] type=1400 audit(0.0:19454): avc: denied { getattr } for path="/persist" dev="sda4" ino=2 scontext=u:r:untrusted_app:s0:c171,c257,c512,c768 tcontext=u:object_r:persist_file:s0 tclass=dir permissive=0
[Native] Initializing FIPS on a background thread.
[ntProviderEndpointProxy] Logging telemetry after IPC failure
[ntProviderEndpointProxy] java.lang.SecurityException: Signature mismatch for package com.packagename
[ntProviderEndpointProxy] 	at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.checkSignatureForPackageIfSignatureKnown(MAMContentProviderBase.java:109)
[ntProviderEndpointProxy] 	at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.verifyCallerIsManaged(MAMContentProviderBase.java:57)
[ntProviderEndpointProxy] 	at com.microsoft.intune.mam.client.ipc.AbstractAppPolicyContentProvider.call(AbstractAppPolicyContentProvider.java:125)
[ntProviderEndpointProxy] 	at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
[ntProviderEndpointProxy] 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
[ntProviderEndpointProxy] 	at android.os.Binder.execTransact(Binder.java:731)
[eIdentityMetadataClient] Cannot set xattrs on sdcard
[AndroidRuntime] FATAL EXCEPTION: Thread-4
[AndroidRuntime] Process: com.packagename, PID: 28373
[AndroidRuntime] java.lang.SecurityException: Signature mismatch for package com.packagename
[AndroidRuntime] 	at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.checkSignatureForPackageIfSignatureKnown(MAMContentProviderBase.java:109)
[AndroidRuntime] 	at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.verifyCallerIsManaged(MAMContentProviderBase.java:57)
[AndroidRuntime] 	at com.microsoft.intune.mam.client.ipc.AbstractAppPolicyContentProvider.call(AbstractAppPolicyContentProvider.java:125)
[AndroidRuntime] 	at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
[AndroidRuntime] 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
[AndroidRuntime] 	at android.os.Binder.execTransact(Binder.java:731)
[ncaughtExceptionHandler] Uncaught exception in app
[ncaughtExceptionHandler] java.lang.SecurityException: Signature mismatch for package com.packagename
[ncaughtExceptionHandler] 	at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.checkSignatureForPackageIfSignatureKnown(MAMContentProviderBase.java:109)
[ncaughtExceptionHandler] 	at com.microsoft.intune.mam.client.ipc.MAMContentProviderBase.verifyCallerIsManaged(MAMContentProviderBase.java:57)
[ncaughtExceptionHandler] 	at com.microsoft.intune.mam.client.ipc.AbstractAppPolicyContentProvider.call(AbstractAppPolicyContentProvider.java:125)
[ncaughtExceptionHandler] 	at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
[ncaughtExceptionHandler] 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:272)
[ncaughtExceptionHandler] 	at android.os.Binder.execTransact(Binder.java:731)
[SQLiteCompatibilityWalFlags] Cannot read global setting sqlite_compatibility_wal_flags - Application state not available
[Native] File encryption hooks installed
[Process] Sending signal. PID: 28373 SIG: 9

**Release Config:**
[TextClassificationManager] Initialized SystemTextClassifier
[AppCompatDelegate] The Activity's LayoutInflater already has a Factory installed so we can not install AppCompat's
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.TypeLoadException: Could not load list of method overrides due to Method not found: void Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)
[MonoDroid]   at AppName.Droid.MainActivity.OnMAMCreate (Android.OS.Bundle savedInstanceState) [0x0006e] in <1906e5d6aa604f598766d65547343a39>:0 
[MonoDroid]   at Microsoft.Intune.Mam.Client.Support.V7.App.MAMAppCompatActivityBase.n_OnMAMCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_p0) [0x00011] in <da70545210724c3b863755035ea42977>:0 
[MonoDroid]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.13(intptr,intptr,intptr)
[s.iConnectStag] JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
[AndroidRuntime] Shutting down VM
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: com.packagename, PID: 31256
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.TypeLoadException: Could not load list of method overrides due to Method not found: void Xamarin.Forms.Platform.Android.IVisualElementRenderer.add_LayoutChange(System.EventHandler`1<Android.Views.View/LayoutChangeEventArgs>)
[AndroidRuntime]   at AppName.Droid.MainActivity.OnMAMCreate (Android.OS.Bundle savedInstanceState) [0x0006e] in <1906e5d6aa604f598766d65547343a39>:0 
[AndroidRuntime]   at Microsoft.Intune.Mam.Client.Support.V7.App.MAMAppCompatActivityBase.n_OnMAMCreate_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_p0) [0x00011] in <da70545210724c3b863755035ea42977>:0 
[AndroidRuntime]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.13(intptr,intptr,intptr)
[AndroidRuntime] 	at md52ca48732e01bb4754f39b2f10e53a059.MainActivity.n_onMAMCreate(Native Method)
[AndroidRuntime] 	at md52ca48732e01bb4754f39b2f10e53a059.MainActivity.onMAMCreate(MainActivity.java:32)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:85)
[AndroidRuntime] 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
[AndroidRuntime] 	at $Proxy10.onMAMCreate(Unknown Source)
[AndroidRuntime] 	at com.microsoft.intune.mam.client.app.ActivityBehaviorImpl.onCreate(ActivityBehaviorImpl.java:317)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:85)
[AndroidRuntime] 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
[AndroidRuntime] 	at $Proxy9.onCreate(Unknown Source)
[AndroidRuntime] 	at com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onCreate(MAMAppCompatActivityBase.java:74)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7144)
[AndroidRuntime] 	at android.app.Activity.performCreate(Activity.java:7135)
[AndroidRuntime] 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
[AndroidRuntime] 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
[AndroidRuntime] 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
[AndroidRuntime] 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[AndroidRuntime] 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[AndroidRuntime] 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:106)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:193)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6680)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[Process] Sending signal. PID: 31256 SIG: 9

**Comment by quantumarun** [comment]
Got resolved now. I had to remove and add both the packages again and that worked.
