### ISSUE TITLE
Project build fails after adding nuget Microsoft.Intune.Maui.Essentials.Android

### ISSUE THREAD

**Issue by gustavoja** [msintuneappsdk/intune-app-sdk-xamarin#61]
Build fails after adding the Microsoft.Intune.Maui.Essentials.Android nuget package on a newly created MAUI application and also a .NET7 Android application 

**To Reproduce**
1. Using visual studio  for mac 17.5.7 (build 6)
2. Create a new .NET MAUI App or an Android Application
3. Add Microsoft.Intune.Maui.Essentials.Android nuget package
4. Try to build the project
5. The build fails with the following message

`/nuget/packages/microsoft.intune.maui.essentials.android/9.5.2-beta2/build/netstandard2.0/Microsoft.Intune.Maui.Essentials.android.targets(9,9): Error: An error occurred trying to start process '.nuget/packages/microsoft.intune.maui.essentials.android/9.5.2-beta2/build/netstandard2.0/BuildTool\bin\BuildToolCLI.bat' with working directory '/Projects/testandroid'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Core.BuildToolCLI.ExecuteBuildToolCLIProcess(Argument input, Argument output, Argument classpath, Argument excludeClasses, Argument reportPath, String workingDirectory, CancellationToken cancellationToken)
   at Core.Mamifier.Mamify()
   at BuildTasks.MamifyFiles.Execute() (testandroid)`

**Expected behavior:**
The project and the app can be built and launch on Visual Studio for mac and Visual Studio for Windows

**Intune App SDK Xamarin Bindings (please complete the following information):**
- What version of the Xamarin Bindings are you using? Are you using the latest version?
- Microsoft.Intune.Maui.Essentials.android" Version="9.5.2-beta" and "9.5.2-beta2" 
- For errors during build, does the app build without Intune SDK Xamarin Bindings integration?
- yes

**Additional context:**
- Doing the same on a Windows PC works as expected
- It seems to be trying to execute a .bat on my mac. Which is not possible

**Comment by gustavoja** [comment]
Hello! Any thoughts on this?

**Comment by bannus** [comment]
This is a known issue and will be resolved in a future release.

###### Internal tracking #24314899
